# Generated by Django 5.0.2 on 2025-04-13 19:08

import converter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='audio_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=converter.models.audio_upload_path),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_file',
            field=models.FileField(max_length=255, upload_to=converter.models.video_upload_path),
        ),
    ]
